"""Dispatch helpers (legal vs policy) for tooling and tests."""

from __future__ import annotations

from sqlalchemy.orm import Session

from app.services.normalized_retrieval import bundle_builder, legal_selector, policy_selector

fetch_normalized_units_for_legal_chunks = legal_selector.fetch_normalized_units_for_legal_chunks
resolve_default_policy_source_version_id = policy_selector.resolve_default_policy_source_version_id
build_policy_evidence_bundle_with_normalized = bundle_builder.build_policy_evidence_bundle_with_normalized
attach_normalized_to_legal_bundle = bundle_builder.attach_normalized_to_legal_bundle
