"""
${slice_title} service
Generated by DSOS scaffold engine for ${phase_id}
Responsibility: ${responsibility}
"""

from __future__ import annotations

from datetime import datetime, UTC
from uuid import uuid4
from sqlalchemy.orm import Session


def build_request_id() -> str:
    return str(uuid4())


def build_audit_payload(*, actor_user_id: int | None, action: str, entity_type: str, entity_id: int | None, before_json=None, after_json=None, meta_json=None) -> dict:
    return {
        "actor_user_id": actor_user_id,
        "action": action,
        "entity_type": entity_type,
        "entity_id": entity_id,
        "before_json": before_json,
        "after_json": after_json,
        "meta_json": meta_json or {},
        "request_id": build_request_id(),
        "created_at": datetime.now(UTC).isoformat(),
    }


def log_write_action(db: Session, **kwargs):
    payload = build_audit_payload(**kwargs)
    return payload
