"""
${slice_title} service
Generated by DSOS scaffold engine for ${phase_id}
Responsibility: ${responsibility}
"""

from __future__ import annotations

from sqlalchemy.orm import Session


def get_active_departments(db: Session):
    """Return active departments. Replace with real Department model query."""
    return []


def get_user_department_memberships(db: Session, user_id: int):
    """Return active memberships for a user."""
    return []


def user_can_access_department(db: Session, user_id: int, department_id: int) -> bool:
    memberships = get_user_department_memberships(db, user_id)
    return any(getattr(m, "department_id", None) == department_id for m in memberships)


def user_can_approve_department(db: Session, user_id: int, department_id: int) -> bool:
    memberships = get_user_department_memberships(db, user_id)
    return any(
        getattr(m, "department_id", None) == department_id and getattr(m, "can_approve", False)
        for m in memberships
    )
