"""
${slice_title} service
Generated by DSOS scaffold engine for ${phase_id}
Responsibility: ${responsibility}
"""

from __future__ import annotations

from sqlalchemy.orm import Session

VALID_SCHEDULE_STATES = {"draft", "submitted", "approved", "rejected", "scheduled", "cancelled"}


def create_schedule_draft(db: Session, *, actor_user_id: int, payload: dict) -> dict:
    return {"status": "draft", "actor_user_id": actor_user_id, "payload": payload}


def submit_schedule(db: Session, *, schedule_id: int, actor_user_id: int) -> dict:
    return {"id": schedule_id, "status": "submitted", "actor_user_id": actor_user_id}


def approve_schedule(db: Session, *, schedule_id: int, actor_user_id: int) -> dict:
    return {"id": schedule_id, "status": "approved", "actor_user_id": actor_user_id}


def reject_schedule(db: Session, *, schedule_id: int, actor_user_id: int, reason: str) -> dict:
    return {"id": schedule_id, "status": "rejected", "actor_user_id": actor_user_id, "reason": reason}


def cancel_schedule(db: Session, *, schedule_id: int, actor_user_id: int) -> dict:
    return {"id": schedule_id, "status": "cancelled", "actor_user_id": actor_user_id}
