"""
${slice_title} service
Generated by DSOS scaffold engine for ${phase_id}
Responsibility: ${responsibility}
"""

from __future__ import annotations

from sqlalchemy.orm import Session


def record_transition(db: Session, *, workflow_name: str, entity_type: str, entity_id: int, state: str, meta_json: dict | None = None) -> dict:
    return {
        "workflow_name": workflow_name,
        "entity_type": entity_type,
        "entity_id": entity_id,
        "state": state,
        "meta_json": meta_json or {},
    }


def get_entity_workflow_history(db: Session, *, entity_type: str, entity_id: int) -> list[dict]:
    return []
