from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TRACKING_DIR = PROJECT_ROOT / "tracking" / "malone"
DEFAULT_MANIFEST = TRACKING_DIR / "malone_manifest_v1.json"
DEFAULT_BUILD_MAP = TRACKING_DIR / "malone_build_map.json"
DEFAULT_TEMPLATE_REGISTRY = PROJECT_ROOT / "tools" / "malone_template_registry.json"
PLACEHOLDER_MARKERS = ["TODO", "Starter scaffold", "Generated by scaffold_malone_phase"]


def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_text(path: Path, content: str, force: bool = False) -> tuple[str, str]:
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and not force:
        existing = path.read_text(encoding="utf-8").strip()
        if existing and not any(marker in existing for marker in PLACEHOLDER_MARKERS):
            return "skipped", str(path)

    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    return "written", str(path)


def rel_from_project(path_str: str) -> Path:
    return PROJECT_ROOT / Path(path_str)


def infer_template_id(path_str: str) -> str:
    normalized = path_str.replace("\\", "/")
    if normalized.endswith("app/services/malone_service.py"):
        return "backend.malone_service"
    if normalized.endswith("app/services/agent_service.py"):
        return "backend.agent_service"
    if normalized.endswith("app/services/intent_service.py"):
        return "backend.intent_service"
    if normalized.endswith("app/services/proposal_service.py"):
        return "backend.proposal_service"
    if normalized.endswith("app/services/prompt_registry_service.py"):
        return "backend.prompt_registry_service"
    if normalized.endswith("app/api/malone_routes.py"):
        return "backend.malone_routes"
    if normalized.endswith("src/pages/MalonePage.jsx"):
        return "frontend.malone_page"
    if normalized.endswith("src/components/malone/ChatPanel.jsx"):
        return "frontend.chat_panel"
    if normalized.endswith("src/components/malone/ProposalPanel.jsx"):
        return "frontend.proposal_panel"
    if normalized.endswith("src/components/malone/AgentRunPanel.jsx"):
        return "frontend.agent_run_panel"
    if normalized.endswith("src/components/malone/VoiceInputButton.jsx"):
        return "frontend.voice_input_button"
    if normalized.endswith("src/lib/maloneApi.js"):
        return "frontend.malone_api"
    raise KeyError(f"No template mapping for {path_str}")


def load_template_registry(path: Path) -> dict[str, Any]:
    return read_json(path)


def render_template(template_path: Path, context: dict[str, Any]) -> str:
    content = template_path.read_text(encoding="utf-8")
    return content.format(**context)


def resolve_targets(manifest: dict[str, Any], build_map: dict[str, Any], phase: str | None) -> list[str]:
    wanted_tasks: set[str] = set()
    if phase:
        matched = [p for p in manifest.get("phases", []) if p.get("name") == phase]
        if not matched:
            available = ", ".join(p.get("name", "") for p in manifest.get("phases", []))
            raise SystemExit(f"Unknown phase '{phase}'. Available phases: {available}")
        for block in matched:
            wanted_tasks.update(block.get("tasks", []))

    outputs: list[str] = []
    for section in ("backend", "frontend"):
        for path_str in build_map.get(section, []):
            template_id = infer_template_id(path_str)
            if not phase:
                outputs.append(path_str)
                continue
            task_aliases = TEMPLATE_TASK_MAP.get(template_id, set())
            if wanted_tasks & task_aliases:
                outputs.append(path_str)
    return outputs


TEMPLATE_TASK_MAP = {
    "backend.malone_service": {"create_malone_service", "answer_mode", "analyst_mode"},
    "backend.agent_service": {"agent_service", "report_agent", "agent_run_tracking"},
    "backend.intent_service": {"create_intent_service"},
    "backend.proposal_service": {"proposal_system", "proposal_approval"},
    "backend.prompt_registry_service": {"setup_prompt_registry"},
    "backend.malone_routes": {"create_malone_service", "answer_mode", "analyst_mode"},
    "frontend.malone_page": {"malone_page"},
    "frontend.chat_panel": {"chat_panel"},
    "frontend.proposal_panel": {"proposal_panel"},
    "frontend.agent_run_panel": {"agent_panel"},
    "frontend.voice_input_button": {"voice_stub", "chat_panel"},
    "frontend.malone_api": {"malone_page", "proposal_system"},
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold Malone v1 slices from tracking manifests.")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--build-map", default=str(DEFAULT_BUILD_MAP))
    parser.add_argument("--template-registry", default=str(DEFAULT_TEMPLATE_REGISTRY))
    parser.add_argument("--phase", help="Only scaffold a single Malone phase from the manifest.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    manifest = read_json(Path(args.manifest))
    build_map = read_json(Path(args.build_map))
    registry = load_template_registry(Path(args.template_registry))

    targets = resolve_targets(manifest, build_map, args.phase)
    context = {
        "generated_note": "Generated by scaffold_malone_phase.py",
        "manifest_version": manifest.get("version", "v1.0"),
        "system_name": manifest.get("system", "malone"),
    }

    actions: list[tuple[str, str]] = []
    for path_str in targets:
        template_id = infer_template_id(path_str)
        template_rel = registry["templates"][template_id]["template"]
        template_path = PROJECT_ROOT / template_rel
        output_path = rel_from_project(path_str)
        rendered = render_template(template_path, context)

        if args.dry_run:
            status = "would_write"
            actions.append((status, str(output_path)))
        else:
            status, out = write_text(output_path, rendered, force=args.force)
            actions.append((status, out))

    for status, out in actions:
        print(f"{status:>11}  {out}")


if __name__ == "__main__":
    main()
