"""
Phase ${phase_id} dependency helpers
Generated by DSOS scaffold engine
Responsibility: ${responsibility}
"""

from __future__ import annotations

from fastapi import HTTPException, status


def require_roles(*allowed_roles: str):
    def _dependency(current_user=None):
        if current_user is None:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Authentication required")
        user_role = getattr(current_user, "role", None)
        if user_role not in allowed_roles:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Insufficient permissions")
        return current_user

    return _dependency


def require_department_scope(current_user=None, department_id: int | None = None):
    return current_user
