"""
Phase ${phase_id} API schemas
Generated by DSOS scaffold engine
Responsibility: ${responsibility}
"""

from __future__ import annotations

from datetime import datetime
from pydantic import BaseModel, Field


class DepartmentCreate(BaseModel):
    code: str = Field(min_length=2, max_length=50)
    name: str = Field(min_length=2, max_length=200)
    description: str | None = None


class DepartmentMembershipUpdate(BaseModel):
    department_id: int
    is_primary: bool = False
    can_approve: bool = False
    is_active: bool = True


class ScheduleSubmitResponse(BaseModel):
    id: int
    status: str
    submitted_at: datetime | None = None


class ScheduleRejectRequest(BaseModel):
    reason: str = Field(min_length=1, max_length=500)


class AuditListItem(BaseModel):
    actor_user_id: int | None = None
    action: str
    entity_type: str
    entity_id: int | None = None
    request_id: str | None = None
    created_at: datetime | None = None
